// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfG7Gmz2Yb_oEb2blN7H5yKk_sJLvo7-Y',
    appId: '1:145475121986:web:222d16d31c45e3231acedb',
    messagingSenderId: '145475121986',
    projectId: 'mylevelapp-71eac',
    authDomain: 'mylevelapp-71eac.firebaseapp.com',
    storageBucket: 'mylevelapp-71eac.firebasestorage.app',
    measurementId: 'G-4TWD356E25',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEo-JJHDFAb2uacOOMr7Q1zRpDb62PMb4',
    appId: '1:145475121986:android:b35a4eda8b7bdc741acedb',
    messagingSenderId: '145475121986',
    projectId: 'mylevelapp-71eac',
    storageBucket: 'mylevelapp-71eac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZK1anBjOzh6QqkqAu6780FdoMAXOzjco',
    appId: '1:145475121986:ios:b1d8db4e7a8fb5ab1acedb',
    messagingSenderId: '145475121986',
    projectId: 'mylevelapp-71eac',
    storageBucket: 'mylevelapp-71eac.firebasestorage.app',
    iosBundleId: 'com.example.missionLeveler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZK1anBjOzh6QqkqAu6780FdoMAXOzjco',
    appId: '1:145475121986:ios:b1d8db4e7a8fb5ab1acedb',
    messagingSenderId: '145475121986',
    projectId: 'mylevelapp-71eac',
    storageBucket: 'mylevelapp-71eac.firebasestorage.app',
    iosBundleId: 'com.example.missionLeveler',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfG7Gmz2Yb_oEb2blN7H5yKk_sJLvo7-Y',
    appId: '1:145475121986:web:7a3c8147540bb36b1acedb',
    messagingSenderId: '145475121986',
    projectId: 'mylevelapp-71eac',
    authDomain: 'mylevelapp-71eac.firebaseapp.com',
    storageBucket: 'mylevelapp-71eac.firebasestorage.app',
    measurementId: 'G-VMXHRMM850',
  );
}
